# Generated by Django 3.2.18 on 2023-04-06 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('type', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=90)),
                ('lname', models.CharField(max_length=90)),
                ('place', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=90)),
                ('phno', models.BigIntegerField()),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.login')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=90)),
                ('lname', models.CharField(max_length=90)),
                ('place', models.CharField(max_length=90)),
                ('phno', models.BigIntegerField()),
                ('email', models.CharField(max_length=90)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.login')),
            ],
        ),
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips', models.CharField(max_length=90)),
                ('date', models.DateField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.staff')),
            ],
        ),
        migrations.CreateModel(
            name='stdymtrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.staff')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=90)),
                ('review', models.CharField(max_length=90)),
                ('date', models.DateField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.parent')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.staff')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=90)),
                ('date', models.DateField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.parent')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.staff')),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=90)),
                ('date', models.DateField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.parent')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.staff')),
            ],
        ),
    ]
