# Generated by Django 3.2.18 on 2023-04-12 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20230410_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='classwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works', models.CharField(max_length=90)),
                ('subject', models.CharField(max_length=90)),
                ('date', models.DateField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.staff')),
            ],
        ),
    ]
