# Generated by Django 3.2.18 on 2023-04-12 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_classwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid', to='sign.login'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.login'),
        ),
    ]
